Vagrant.configure(2) do |config|
  config.vm.define "with-docker"
  config.vm.provider "virtualbox" do |v|
     v.name = "_withDocker"
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update && apt-get -y upgrade
  SHELL
  config.vm.provision "docker" do |d|
     d.build_image "/vagrant/docker/Tomcat7PuppetFull", args: "-t tomcat7dockerfromvagrant"
     d.run "tomcat7dockerfromvagrant", args: "-p 8080:8080"
  end
  config.vm.network :forwarded_port, host: 8090, guest: 8080
end

